# Scoping

In the Scoping stage, you will choose a paper to reproduce. , or be assigned one. Chapter 2 describes the steps for defining the scope of a reproduction exercise. ***Use [Survey 1](https://berkeley.qualtrics.com/jfe/form/SV_3UWe5xu3qjeh0c5) to record your work for this stage.***

## Steps

Before you invest any time in reading or summarizing a paper, complete steps 2.1.1–2.1.2: 

### Check records on the ACRE platform. {#check-acre}

Check the [ACRE database](ADD LINK) for previous assessments of the same paper. If there are none, create the first entry. If there are previous entries, check if the **paper status** is “open to reproductions”, and create a new entry^[If the paper status is "closed to reproductions", ACRE has documented interactions between previous reproductors and original authors, so it is not possible to access any further required materials.].   

### Verify that reproduction package exist.  {#verify-rep-mat}

Verify that the paper has reproduction package (consult the unofficial AEA [Data and Code Guidance](https://social-science-data-editors.github.io/guidance/Verification_guidance.html) to determine whether you have everything you need before you start). If any of the materials are missing, use our records to check if requests to authors for these materials have been made before. If nobody has yet submitted a similar request, contact the authors using language suggested [here](LINK), making sure to copy (acre@berkeley.edu). If the authors have been contacted before and the information is still missing, submit a request for closing the paper for further reproductions and choose another paper.

<!--  
### Advise on scoping for different course length

2-week courses should not try to improve reproducibility from raw data
-->

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg .tg-baqh{text-align:center;vertical-align:top}
.tg .tg-c3ow{border-color:inherit;text-align:center;vertical-align:top}
.tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
.tg .tg-dvpl{border-color:inherit;text-align:right;vertical-align:top}
.tg .tg-0lax{text-align:left;vertical-align:top}
</style>
<table class="tg">
  <tr>
    <th class="tg-0pky"></th>
    <th class="tg-c3ow" colspan="2">2 week</th>
    <th class="tg-c3ow" colspan="2">1 month</th>
    <th class="tg-c3ow" colspan="2">1 semester</th>
  </tr>
  <tr>
    <td class="tg-0pky"></td>
    <td class="tg-0pky">analysis data</td>
    <td class="tg-0pky">raw data</td>
    <td class="tg-0pky">analysis data</td>
    <td class="tg-0pky">raw data</td>
    <td class="tg-0pky">analysis data</td>
    <td class="tg-0pky">raw data</td>
  </tr>
  <tr>
    <td class="tg-dvpl">scoping</td>
    <td class="tg-c3ow" colspan="2">10% (1 day)</td>
    <td class="tg-c3ow" colspan="2">5% (1 day)</td>
    <td class="tg-c3ow" colspan="2">3% (3 days)</td>
  </tr>
  <tr>
    <td class="tg-dvpl">Assessment</td>
    <td class="tg-c3ow" colspan="2">25%</td>
    <td class="tg-c3ow" colspan="2">15%</td>
    <td class="tg-c3ow" colspan="2">7%</td>
  </tr>
  <tr>
    <td class="tg-0pky">Improvement</td>
    <td class="tg-c3ow">20%</td>
    <td class="tg-c3ow">0%</td>
    <td class="tg-c3ow" colspan="2">40%</td>
    <td class="tg-c3ow">20%</td>
    <td class="tg-c3ow">30%</td>
  </tr>
  <tr>
    <td class="tg-0pky">Robustness</td>
    <td class="tg-c3ow" colspan="2">40%</td>
    <td class="tg-c3ow" colspan="2">30%</td>
    <td class="tg-c3ow" colspan="2">30%</td>
  </tr>
  <tr>
    <td class="tg-0lax">Extension</td>
    <td class="tg-baqh">5%</td>
    <td class="tg-baqh">0%</td>
    <td class="tg-baqh" colspan="2">10%</td>
    <td class="tg-baqh" colspan="2">10%</td>
  </tr>
</table>


### Read and summarize the paper. {#read-sum}

Depending on how much time you have, we recommend that you write a short summary of the paper. This will help remind you of the key elements to focus on for the reproduction, and to demonstrate your understanding of the paper (for yourself and potentially for the original author).

Read the paper and write a two-page summary, answering the following: What is the main question the paper attempts to answer? What methodologies doe is employ? What data sources do the authors use?

### Declare scope of the exercise.

Declare if your assessment will be of all of the paper’s results (**complete**) or just the **main results**, and if you will aim to start with **raw data** or **processed data**. Find definitions of these concepts below. 

ADD description that scoping involves chosing paper, output and level of depth to improve. Given output assessment is all the way to raw data. But improvement and robustness should be limited to the amount of time is provided for the excercise.  


#### Define your reproduction margins.

##### Define the *extensive margin*: outputs to reproduced {#outputs}  

Define whether you will attempt to reproduce all of your chosen paper’s results or just the main results. 
  - **Complete**: A successful complete reproduction obtains all of the same estimates presented in the chosen paper. This includes tables, figures, and inline estimates, both in the main body of the paper and the appendices.
  - **Main results**: A successful reproduction of main results obtains the same estimates as those highlighted in the chosen paper’s abstract, introduction, or conclusion. If no estimate is highlighted, you should choose the main result and declare it at the beggining of the reproduction.

###### Describe the types of output.   

Broadly describe the outputs you will attempt to reproduce.

  - **Tables:** Describe how to cite record location. 
  - **Figures:**  ADD   
  - **In-line:**  ADD    


##### Define the *intensive margin*: depth of reproduction in terms of original data. {#intensive}

 - **Raw data** sets are unmodified files obtained by the authors from the sources cited in the paper. Raw data from which personally identifiable information (PII) has been removed is still considered raw. All other modifications to raw data make it *processed*.
 - **Processed data** are raw data sets that have gone through any transformation other than the removal of PII. There are two kinds of processed data:
      - *Intermediate data* are not directly used as final input for analyses presented in the final paper (including appendices). Intermediate data should not contain direct identifiers.
      - *Analytic data* is used as the final input in a workflow in order to produce a statistic displayed in the paper (including appendices).

###### Classifying a data set
A data set may be classified as **raw** if it fits any of the following criteria:    

 - The data is stored in a folder or file labeled as “raw”.  
 - The data set is not the output of any code script in the reproduction package.    
 - The same data file can be independently obtained from the data source cited in the paper.  

A data set may be classified as **analytic** if it fits any of the following criteria:   

 - The data is stored in a folder or file labeled as “analytic” or “analysis.”
 - The data set is the last input required to produce some of the output (formatted or unformatted) of the paper.
  


## Sample strategies for scoping  

ADD. 

### Strategy 1: 

1. Attempt to reproduce the paper’s main estimates.
2. Attempt to reproduce two main tables and/or two main figures.
3. Try to make improvements to these outputs. 
4. Try to reproduce the rest of the paper.
   

### Strategy 2:  

1. Attempt to reproduce all outputs resulting from the analytic data.
2. Once you can do that,  try to make improvements.
3. If you can make improvements, attempt to reproduce the outputs starting from raw data. (or in parallel?)
 
 
 
