# Examples of Reproduction Diagrams  

## Stylized examples

### Complete reproduction package
Below is an example of output from the ACRE Diagram builder for a display item that can be fully constructed using the files contained in the reproduction package. The diagram displays files as outputs and inputs to code scripts all the way down to the raw data.

          table 1
            └───[code] formatting_table1.R
                ├───output1_part1.txt  
                |   └───[code] output_table1.do           
                |       └───[data] analysis_data01.csv
                |          └───[code] data_cleaning01.R
                |             └───[data] survey_01raw.csv
                └───output1_part2.txt  
                    └───[code] output_table2.do           
                        └───[data] analysis_data02.csv
                           └───[code] data_cleaning02.R
                              └───[data] admin_01raw.csv  



### Raw data and analytic data are available, but cleaning code is missing.
Below is an example of output from the ACRE Diagram Builder for a display item that is missing some of the code needed to generate it from the raw data. In this case, we have assumed there are missing code scripts that at some point take in `survey_01raw.csv` and `admin_01raw.csv`, and eventually output `analysis_data01.csv` and `analysis_data02.csv`, though this requires the reproducer's discretion.

          table 1
            └───[code] formatting_table1.R
                ├───output1_part1.txt  
                |   └───[code] output_table1.do           
                |       └───[data] analysis_data01.csv
                |          └───[code] MISSING FILE(S)
                |             └───[data] survey_01raw.csv
                └───output1_part2.txt  
                    └───[code] output_table2.do           
                        └───[data] analysis_data02.csv
                           └───[code] MISSING FILE(S)
                              └───[data] admin_01raw.csv  

## Examples from real reproduction attempts


### Possibly missing code for producing a display item. (This is from a reproduction attempt conducted as part of a UC Berkeley Development Economics course.)

This reproduction diagram fragment likely shows a missing piece of code. In a complete reproduction package there are no unused files and all final outputs are display items. `cps2018.dta` and `cps_march2017.dta` are included as inputs in the reproduction kit, but never used to make a display item, i.e., there is no piece of code that is listed as using them as inputs. Likewise, `PublicSalary.dta` is listed as a final output, meaning it, too, is not used to make a display item since it is not listed as an input for any code script. Perhaps `Paper2_PoExitDataset.dta` is made by a missing code script that takes `PublicSalary.dta`, `cps2018.dta`, and `cps_march2017.dta` as inputs? It may be the case that the only way to find out for sure is to contact the study author(s), in which case, such a diagram can be used to help them identify any missing files.

        PublicSalary.dta
        |___MakeData2.do
            |___Paper2_ProviderDataset.dta
            |___Paper2_SSPDataset_wIRT_final.dta
            |___PublicFacilitySurvey_clean.dta

        Table1.xml
        |___Table1.do
            |___ProviderData.dta
            |   |___MakeData4.do
            |       |___Paper2_PoExitDataset.dta
            |       |___Paper2_ProviderDataset.dta
            |       |___Paper2_SSPDataset_wIRT_final.dta
            |___VillageDataset.dta
            |   |___MakeData8.do
            |       |___Paper2_HouseholdDataset1.dta
            |       |___Paper2_VillageDataset.dta
            |___HouseholdDataset.dta
                |___MakeData8.do
                    |___Paper2_HouseholdDataset1.dta
                    |___Paper2_VillageDataset.dta

        Unusued data sources:
        cps2018.dta
        cps_march2017.dta  

### Long, complicated tree. (This is from a reproduction attempt conducted as part of a UC Berkeley Development Economics course.)

This diagram shows that the production of a given display item may be very complicated, highlighting the usefulness of the ACRE Diagram Builder as a visualization tool. In reproducing such a complicated display item, it can be useful to have such a diagram to determine, for example, the order in which code scripts should be run, what files might depend on a faulty code script, or which files are necessary to keep if the goal is to only produce the specific display item.

```{style="max-height: 300px;"}
        results_days.dta
        |___lightspaper_replication.do
            |___isocvout.dbf
            |   |___v4cvggini_bycountry_prep.aml
            |       |___ctryliggrid
            |       |   |___v4unzip.bat
            |       |       |___rad_cal.tar
            |       |       |___phys_geo.zip
            |       |       |___world_avg_fixed.tfw
            |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |___malaria_ecology.zip
            |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |___gasflares.zip
            |       |       |___F%sy%.v4.tar
            |       |       |___boundaries.zip
            |       |___l%sy%nm
            |       |   |___v4lightsprep.aml
            |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___world_avg.tfw
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___gluareag_alpha1.asc
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___F%sy%.v4b_web.cf_cvg.tif
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___F%sy%.v4b_web.cf_cvg.tfw
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___world_avg.tif
            |       |           |___v4unzip.bat
            |       |               |___rad_cal.tar
            |       |               |___phys_geo.zip
            |       |               |___world_avg_fixed.tfw
            |       |               |___af_grumpv1_ppoints_csv.zip
            |       |               |___gl_grumpv1_area_ascii_30.zip
            |       |               |___malaria_ecology.zip
            |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |               |___gasflares.zip
            |       |               |___F%sy%.v4.tar
            |       |               |___boundaries.zip
            |       |___cvg%sy%
            |       |   |___v4lightsprep.aml
            |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___world_avg.tfw
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___gluareag_alpha1.asc
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___F%sy%.v4b_web.cf_cvg.tif
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___F%sy%.v4b_web.cf_cvg.tfw
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___world_avg.tif
            |       |           |___v4unzip.bat
            |       |               |___rad_cal.tar
            |       |               |___phys_geo.zip
            |       |               |___world_avg_fixed.tfw
            |       |               |___af_grumpv1_ppoints_csv.zip
            |       |               |___gl_grumpv1_area_ascii_30.zip
            |       |               |___malaria_ecology.zip
            |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |               |___gasflares.zip
            |       |               |___F%sy%.v4.tar
            |       |               |___boundaries.zip
            |       |___isocvgst.dbf
            |       |   |___pre_aml.do
            |       |       |___afpv1.csv
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___ctrynum.dbf
            |       |___ginistrt.dbf
            |           |___pre_aml.do
            |               |___afpv1.csv
            |               |   |___v4unzip.bat
            |               |       |___rad_cal.tar
            |               |       |___phys_geo.zip
            |               |       |___world_avg_fixed.tfw
            |               |       |___af_grumpv1_ppoints_csv.zip
            |               |       |___gl_grumpv1_area_ascii_30.zip
            |               |       |___malaria_ecology.zip
            |               |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |               |       |___gasflares.zip
            |               |       |___F%sy%.v4.tar
            |               |       |___boundaries.zip
            |               |___ctrynum.dbf
            |___ginioutu.dbf
            |   |___v4cvggini_bycountry_prep.aml
            |       |___ctryliggrid
            |       |   |___v4unzip.bat
            |       |       |___rad_cal.tar
            |       |       |___phys_geo.zip
            |       |       |___world_avg_fixed.tfw
            |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |___malaria_ecology.zip
            |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |___gasflares.zip
            |       |       |___F%sy%.v4.tar
            |       |       |___boundaries.zip
            |       |___l%sy%nm
            |       |   |___v4lightsprep.aml
            |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___world_avg.tfw
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___gluareag_alpha1.asc
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___F%sy%.v4b_web.cf_cvg.tif
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___F%sy%.v4b_web.cf_cvg.tfw
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___world_avg.tif
            |       |           |___v4unzip.bat
            |       |               |___rad_cal.tar
            |       |               |___phys_geo.zip
            |       |               |___world_avg_fixed.tfw
            |       |               |___af_grumpv1_ppoints_csv.zip
            |       |               |___gl_grumpv1_area_ascii_30.zip
            |       |               |___malaria_ecology.zip
            |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |               |___gasflares.zip
            |       |               |___F%sy%.v4.tar
            |       |               |___boundaries.zip
            |       |___cvg%sy%
            |       |   |___v4lightsprep.aml
            |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___world_avg.tfw
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___gluareag_alpha1.asc
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___F%sy%.v4b_web.cf_cvg.tif
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___F%sy%.v4b_web.cf_cvg.tfw
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___world_avg.tif
            |       |           |___v4unzip.bat
            |       |               |___rad_cal.tar
            |       |               |___phys_geo.zip
            |       |               |___world_avg_fixed.tfw
            |       |               |___af_grumpv1_ppoints_csv.zip
            |       |               |___gl_grumpv1_area_ascii_30.zip
            |       |               |___malaria_ecology.zip
            |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |               |___gasflares.zip
            |       |               |___F%sy%.v4.tar
            |       |               |___boundaries.zip
            |       |___isocvgst.dbf
            |       |   |___pre_aml.do
            |       |       |___afpv1.csv
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___ctrynum.dbf
            |       |___ginistrt.dbf
            |           |___pre_aml.do
            |               |___afpv1.csv
            |               |   |___v4unzip.bat
            |               |       |___rad_cal.tar
            |               |       |___phys_geo.zip
            |               |       |___world_avg_fixed.tfw
            |               |       |___af_grumpv1_ppoints_csv.zip
            |               |       |___gl_grumpv1_area_ascii_30.zip
            |               |       |___malaria_ecology.zip
            |               |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |               |       |___gasflares.zip
            |               |       |___F%sy%.v4.tar
            |               |       |___boundaries.zip
            |               |___ctrynum.dbf
            |___global_total_dn_uncal_longdiff9206.dta
            |   |___v4lights_stataprep_uncal.do
            |       |___ctryoutu.dbf
            |       |   |___v4ctrytables_uncal.aml
            |       |       |___ctryliggrid
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___l%sy%nm
            |       |       |   |___v4lightsprep.aml
            |       |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___world_avg.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___gluareag_alpha1.asc
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.cf_cvg.tif
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.cf_cvg.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___world_avg.tif
            |       |       |           |___v4unzip.bat
            |       |       |               |___rad_cal.tar
            |       |       |               |___phys_geo.zip
            |       |       |               |___world_avg_fixed.tfw
            |       |       |               |___af_grumpv1_ppoints_csv.zip
            |       |       |               |___gl_grumpv1_area_ascii_30.zip
            |       |       |               |___malaria_ecology.zip
            |       |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |               |___gasflares.zip
            |       |       |               |___F%sy%.v4.tar
            |       |       |               |___boundaries.zip
            |       |       |___cvg%sy%
            |       |       |   |___v4lightsprep.aml
            |       |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___world_avg.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___gluareag_alpha1.asc
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.cf_cvg.tif
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.cf_cvg.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___world_avg.tif
            |       |       |           |___v4unzip.bat
            |       |       |               |___rad_cal.tar
            |       |       |               |___phys_geo.zip
            |       |       |               |___world_avg_fixed.tfw
            |       |       |               |___af_grumpv1_ppoints_csv.zip
            |       |       |               |___gl_grumpv1_area_ascii_30.zip
            |       |       |               |___malaria_ecology.zip
            |       |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |               |___gasflares.zip
            |       |       |               |___F%sy%.v4.tar
            |       |       |               |___boundaries.zip
            |       |       |___gluareag
            |       |       |   |___v4lightsprep.aml
            |       |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___world_avg.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___gluareag_alpha1.asc
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.cf_cvg.tif
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.cf_cvg.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___world_avg.tif
            |       |       |           |___v4unzip.bat
            |       |       |               |___rad_cal.tar
            |       |       |               |___phys_geo.zip
            |       |       |               |___world_avg_fixed.tfw
            |       |       |               |___af_grumpv1_ppoints_csv.zip
            |       |       |               |___gl_grumpv1_area_ascii_30.zip
            |       |       |               |___malaria_ecology.zip
            |       |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |               |___gasflares.zip
            |       |       |               |___F%sy%.v4.tar
            |       |       |               |___boundaries.zip
            |       |       |___ctrynum.dbf
            |       |       |___gasflares.shp
            |       |       |   |___merge_gf.pyw
            |       |       |       |___afprimates.csv
            |       |       |       |   |___pre_aml.do
            |       |       |       |       |___afpv1.csv
            |       |       |       |       |   |___v4unzip.bat
            |       |       |       |       |       |___rad_cal.tar
            |       |       |       |       |       |___phys_geo.zip
            |       |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |       |___gasflares.zip
            |       |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |       |___boundaries.zip
            |       |       |       |       |___ctrynum.dbf
            |       |       |       |___gas flares by country
            |       |       |           |___v4unzip.bat
            |       |       |               |___rad_cal.tar
            |       |       |               |___phys_geo.zip
            |       |       |               |___world_avg_fixed.tfw
            |       |       |               |___af_grumpv1_ppoints_csv.zip
            |       |       |               |___gl_grumpv1_area_ascii_30.zip
            |       |       |               |___malaria_ecology.zip
            |       |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |               |___gasflares.zip
            |       |       |               |___F%sy%.v4.tar
            |       |       |               |___boundaries.zip
            |       |       |___glp00ag
            |       |           |___v4unzip.bat
            |       |               |___rad_cal.tar
            |       |               |___phys_geo.zip
            |       |               |___world_avg_fixed.tfw
            |       |               |___af_grumpv1_ppoints_csv.zip
            |       |               |___gl_grumpv1_area_ascii_30.zip
            |       |               |___malaria_ecology.zip
            |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |               |___gasflares.zip
            |       |               |___F%sy%.v4.tar
            |       |               |___boundaries.zip
            |       |___dhselect.xls
            |       |___wb_dq.xls
            |       |___ctryout2.dbf
            |       |   |___v4ctrytables_uncal.aml
            |       |       |___ctryliggrid
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___l%sy%nm
            |       |       |   |___v4lightsprep.aml
            |       |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___world_avg.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___gluareag_alpha1.asc
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.cf_cvg.tif
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.cf_cvg.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___world_avg.tif
            |       |       |           |___v4unzip.bat
            |       |       |               |___rad_cal.tar
            |       |       |               |___phys_geo.zip
            |       |       |               |___world_avg_fixed.tfw
            |       |       |               |___af_grumpv1_ppoints_csv.zip
            |       |       |               |___gl_grumpv1_area_ascii_30.zip
            |       |       |               |___malaria_ecology.zip
            |       |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |               |___gasflares.zip
            |       |       |               |___F%sy%.v4.tar
            |       |       |               |___boundaries.zip
            |       |       |___cvg%sy%
            |       |       |   |___v4lightsprep.aml
            |       |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___world_avg.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___gluareag_alpha1.asc
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.cf_cvg.tif
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.cf_cvg.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___world_avg.tif
            |       |       |           |___v4unzip.bat
            |       |       |               |___rad_cal.tar
            |       |       |               |___phys_geo.zip
            |       |       |               |___world_avg_fixed.tfw
            |       |       |               |___af_grumpv1_ppoints_csv.zip
            |       |       |               |___gl_grumpv1_area_ascii_30.zip
            |       |       |               |___malaria_ecology.zip
            |       |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |               |___gasflares.zip
            |       |       |               |___F%sy%.v4.tar
            |       |       |               |___boundaries.zip
            |       |       |___gluareag
            |       |       |   |___v4lightsprep.aml
            |       |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___world_avg.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___gluareag_alpha1.asc
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.cf_cvg.tif
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.cf_cvg.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___world_avg.tif
            |       |       |           |___v4unzip.bat
            |       |       |               |___rad_cal.tar
            |       |       |               |___phys_geo.zip
            |       |       |               |___world_avg_fixed.tfw
            |       |       |               |___af_grumpv1_ppoints_csv.zip
            |       |       |               |___gl_grumpv1_area_ascii_30.zip
            |       |       |               |___malaria_ecology.zip
            |       |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |               |___gasflares.zip
            |       |       |               |___F%sy%.v4.tar
            |       |       |               |___boundaries.zip
            |       |       |___ctrynum.dbf
            |       |       |___gasflares.shp
            |       |       |   |___merge_gf.pyw
            |       |       |       |___afprimates.csv
            |       |       |       |   |___pre_aml.do
            |       |       |       |       |___afpv1.csv
            |       |       |       |       |   |___v4unzip.bat
            |       |       |       |       |       |___rad_cal.tar
            |       |       |       |       |       |___phys_geo.zip
            |       |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |       |___gasflares.zip
            |       |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |       |___boundaries.zip
            |       |       |       |       |___ctrynum.dbf
            |       |       |       |___gas flares by country
            |       |       |           |___v4unzip.bat
            |       |       |               |___rad_cal.tar
            |       |       |               |___phys_geo.zip
            |       |       |               |___world_avg_fixed.tfw
            |       |       |               |___af_grumpv1_ppoints_csv.zip
            |       |       |               |___gl_grumpv1_area_ascii_30.zip
            |       |       |               |___malaria_ecology.zip
            |       |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |               |___gasflares.zip
            |       |       |               |___F%sy%.v4.tar
            |       |       |               |___boundaries.zip
            |       |       |___glp00ag
            |       |           |___v4unzip.bat
            |       |               |___rad_cal.tar
            |       |               |___phys_geo.zip
            |       |               |___world_avg_fixed.tfw
            |       |               |___af_grumpv1_ppoints_csv.zip
            |       |               |___gl_grumpv1_area_ascii_30.zip
            |       |               |___malaria_ecology.zip
            |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |               |___gasflares.zip
            |       |               |___F%sy%.v4.tar
            |       |               |___boundaries.zip
            |       |___ginioutu.dbf
            |       |   |___v4cvggini_bycountry_prep.aml
            |       |       |___ctryliggrid
            |       |       |   |___v4unzip.bat
            |       |       |       |___rad_cal.tar
            |       |       |       |___phys_geo.zip
            |       |       |       |___world_avg_fixed.tfw
            |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |___malaria_ecology.zip
            |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |___gasflares.zip
            |       |       |       |___F%sy%.v4.tar
            |       |       |       |___boundaries.zip
            |       |       |___l%sy%nm
            |       |       |   |___v4lightsprep.aml
            |       |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___world_avg.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___gluareag_alpha1.asc
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.cf_cvg.tif
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.cf_cvg.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___world_avg.tif
            |       |       |           |___v4unzip.bat
            |       |       |               |___rad_cal.tar
            |       |       |               |___phys_geo.zip
            |       |       |               |___world_avg_fixed.tfw
            |       |       |               |___af_grumpv1_ppoints_csv.zip
            |       |       |               |___gl_grumpv1_area_ascii_30.zip
            |       |       |               |___malaria_ecology.zip
            |       |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |               |___gasflares.zip
            |       |       |               |___F%sy%.v4.tar
            |       |       |               |___boundaries.zip
            |       |       |___cvg%sy%
            |       |       |   |___v4lightsprep.aml
            |       |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___world_avg.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___gluareag_alpha1.asc
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.cf_cvg.tif
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___F%sy%.v4b_web.cf_cvg.tfw
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___world_avg.tif
            |       |       |           |___v4unzip.bat
            |       |       |               |___rad_cal.tar
            |       |       |               |___phys_geo.zip
            |       |       |               |___world_avg_fixed.tfw
            |       |       |               |___af_grumpv1_ppoints_csv.zip
            |       |       |               |___gl_grumpv1_area_ascii_30.zip
            |       |       |               |___malaria_ecology.zip
            |       |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |               |___gasflares.zip
            |       |       |               |___F%sy%.v4.tar
            |       |       |               |___boundaries.zip
            |       |       |___isocvgst.dbf
            |       |       |   |___pre_aml.do
            |       |       |       |___afpv1.csv
            |       |       |       |   |___v4unzip.bat
            |       |       |       |       |___rad_cal.tar
            |       |       |       |       |___phys_geo.zip
            |       |       |       |       |___world_avg_fixed.tfw
            |       |       |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |       |       |___malaria_ecology.zip
            |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |       |       |___gasflares.zip
            |       |       |       |       |___F%sy%.v4.tar
            |       |       |       |       |___boundaries.zip
            |       |       |       |___ctrynum.dbf
            |       |       |___ginistrt.dbf
            |       |           |___pre_aml.do
            |       |               |___afpv1.csv
            |       |               |   |___v4unzip.bat
            |       |               |       |___rad_cal.tar
            |       |               |       |___phys_geo.zip
            |       |               |       |___world_avg_fixed.tfw
            |       |               |       |___af_grumpv1_ppoints_csv.zip
            |       |               |       |___gl_grumpv1_area_ascii_30.zip
            |       |               |       |___malaria_ecology.zip
            |       |               |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |               |       |___gasflares.zip
            |       |               |       |___F%sy%.v4.tar
            |       |               |       |___boundaries.zip
            |       |               |___ctrynum.dbf
            |       |___wdi_limited.dta
            |       |___imf_dds.xls
            |       |___ginistata_uncal.dta
            |           |___v4ginicalc_uncal.do
            |               |___ginioutu.dbf
            |                   |___v4cvggini_bycountry_prep.aml
            |                       |___ctryliggrid
            |                       |   |___v4unzip.bat
            |                       |       |___rad_cal.tar
            |                       |       |___phys_geo.zip
            |                       |       |___world_avg_fixed.tfw
            |                       |       |___af_grumpv1_ppoints_csv.zip
            |                       |       |___gl_grumpv1_area_ascii_30.zip
            |                       |       |___malaria_ecology.zip
            |                       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |                       |       |___gasflares.zip
            |                       |       |___F%sy%.v4.tar
            |                       |       |___boundaries.zip
            |                       |___l%sy%nm
            |                       |   |___v4lightsprep.aml
            |                       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
            |                       |       |   |___v4unzip.bat
            |                       |       |       |___rad_cal.tar
            |                       |       |       |___phys_geo.zip
            |                       |       |       |___world_avg_fixed.tfw
            |                       |       |       |___af_grumpv1_ppoints_csv.zip
            |                       |       |       |___gl_grumpv1_area_ascii_30.zip
            |                       |       |       |___malaria_ecology.zip
            |                       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |                       |       |       |___gasflares.zip
            |                       |       |       |___F%sy%.v4.tar
            |                       |       |       |___boundaries.zip
            |                       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
            |                       |       |   |___v4unzip.bat
            |                       |       |       |___rad_cal.tar
            |                       |       |       |___phys_geo.zip
            |                       |       |       |___world_avg_fixed.tfw
            |                       |       |       |___af_grumpv1_ppoints_csv.zip
            |                       |       |       |___gl_grumpv1_area_ascii_30.zip
            |                       |       |       |___malaria_ecology.zip
            |                       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |                       |       |       |___gasflares.zip
            |                       |       |       |___F%sy%.v4.tar
            |                       |       |       |___boundaries.zip
            |                       |       |___world_avg.tfw
            |                       |       |   |___v4unzip.bat
            |                       |       |       |___rad_cal.tar
            |                       |       |       |___phys_geo.zip
            |                       |       |       |___world_avg_fixed.tfw
            |                       |       |       |___af_grumpv1_ppoints_csv.zip
            |                       |       |       |___gl_grumpv1_area_ascii_30.zip
            |                       |       |       |___malaria_ecology.zip
            |                       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |                       |       |       |___gasflares.zip
            |                       |       |       |___F%sy%.v4.tar
            |                       |       |       |___boundaries.zip
            |                       |       |___gluareag_alpha1.asc
            |                       |       |   |___v4unzip.bat
            |                       |       |       |___rad_cal.tar
            |                       |       |       |___phys_geo.zip
            |                       |       |       |___world_avg_fixed.tfw
            |                       |       |       |___af_grumpv1_ppoints_csv.zip
            |                       |       |       |___gl_grumpv1_area_ascii_30.zip
            |                       |       |       |___malaria_ecology.zip
            |                       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |                       |       |       |___gasflares.zip
            |                       |       |       |___F%sy%.v4.tar
            |                       |       |       |___boundaries.zip
            |                       |       |___F%sy%.v4b_web.cf_cvg.tif
            |                       |       |   |___v4unzip.bat
            |                       |       |       |___rad_cal.tar
            |                       |       |       |___phys_geo.zip
            |                       |       |       |___world_avg_fixed.tfw
            |                       |       |       |___af_grumpv1_ppoints_csv.zip
            |                       |       |       |___gl_grumpv1_area_ascii_30.zip
            |                       |       |       |___malaria_ecology.zip
            |                       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |                       |       |       |___gasflares.zip
            |                       |       |       |___F%sy%.v4.tar
            |                       |       |       |___boundaries.zip
            |                       |       |___F%sy%.v4b_web.cf_cvg.tfw
            |                       |       |   |___v4unzip.bat
            |                       |       |       |___rad_cal.tar
            |                       |       |       |___phys_geo.zip
            |                       |       |       |___world_avg_fixed.tfw
            |                       |       |       |___af_grumpv1_ppoints_csv.zip
            |                       |       |       |___gl_grumpv1_area_ascii_30.zip
            |                       |       |       |___malaria_ecology.zip
            |                       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |                       |       |       |___gasflares.zip
            |                       |       |       |___F%sy%.v4.tar
            |                       |       |       |___boundaries.zip
            |                       |       |___world_avg.tif
            |                       |           |___v4unzip.bat
            |                       |               |___rad_cal.tar
            |                       |               |___phys_geo.zip
            |                       |               |___world_avg_fixed.tfw
            |                       |               |___af_grumpv1_ppoints_csv.zip
            |                       |               |___gl_grumpv1_area_ascii_30.zip
            |                       |               |___malaria_ecology.zip
            |                       |               |___gl_gpwv3_pcount_00_wrk_25.zip
            |                       |               |___gasflares.zip
            |                       |               |___F%sy%.v4.tar
            |                       |               |___boundaries.zip
            |                       |___cvg%sy%
            |                       |   |___v4lightsprep.aml
            |                       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
            |                       |       |   |___v4unzip.bat
            |                       |       |       |___rad_cal.tar
            |                       |       |       |___phys_geo.zip
            |                       |       |       |___world_avg_fixed.tfw
            |                       |       |       |___af_grumpv1_ppoints_csv.zip
            |                       |       |       |___gl_grumpv1_area_ascii_30.zip
            |                       |       |       |___malaria_ecology.zip
            |                       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |                       |       |       |___gasflares.zip
            |                       |       |       |___F%sy%.v4.tar
            |                       |       |       |___boundaries.zip
            |                       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
            |                       |       |   |___v4unzip.bat
            |                       |       |       |___rad_cal.tar
            |                       |       |       |___phys_geo.zip
            |                       |       |       |___world_avg_fixed.tfw
            |                       |       |       |___af_grumpv1_ppoints_csv.zip
            |                       |       |       |___gl_grumpv1_area_ascii_30.zip
            |                       |       |       |___malaria_ecology.zip
            |                       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |                       |       |       |___gasflares.zip
            |                       |       |       |___F%sy%.v4.tar
            |                       |       |       |___boundaries.zip
            |                       |       |___world_avg.tfw
            |                       |       |   |___v4unzip.bat
            |                       |       |       |___rad_cal.tar
            |                       |       |       |___phys_geo.zip
            |                       |       |       |___world_avg_fixed.tfw
            |                       |       |       |___af_grumpv1_ppoints_csv.zip
            |                       |       |       |___gl_grumpv1_area_ascii_30.zip
            |                       |       |       |___malaria_ecology.zip
            |                       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |                       |       |       |___gasflares.zip
            |                       |       |       |___F%sy%.v4.tar
            |                       |       |       |___boundaries.zip
            |                       |       |___gluareag_alpha1.asc
            |                       |       |   |___v4unzip.bat
            |                       |       |       |___rad_cal.tar
            |                       |       |       |___phys_geo.zip
            |                       |       |       |___world_avg_fixed.tfw
            |                       |       |       |___af_grumpv1_ppoints_csv.zip
            |                       |       |       |___gl_grumpv1_area_ascii_30.zip
            |                       |       |       |___malaria_ecology.zip
            |                       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |                       |       |       |___gasflares.zip
            |                       |       |       |___F%sy%.v4.tar
            |                       |       |       |___boundaries.zip
            |                       |       |___F%sy%.v4b_web.cf_cvg.tif
            |                       |       |   |___v4unzip.bat
            |                       |       |       |___rad_cal.tar
            |                       |       |       |___phys_geo.zip
            |                       |       |       |___world_avg_fixed.tfw
            |                       |       |       |___af_grumpv1_ppoints_csv.zip
            |                       |       |       |___gl_grumpv1_area_ascii_30.zip
            |                       |       |       |___malaria_ecology.zip
            |                       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |                       |       |       |___gasflares.zip
            |                       |       |       |___F%sy%.v4.tar
            |                       |       |       |___boundaries.zip
            |                       |       |___F%sy%.v4b_web.cf_cvg.tfw
            |                       |       |   |___v4unzip.bat
            |                       |       |       |___rad_cal.tar
            |                       |       |       |___phys_geo.zip
            |                       |       |       |___world_avg_fixed.tfw
            |                       |       |       |___af_grumpv1_ppoints_csv.zip
            |                       |       |       |___gl_grumpv1_area_ascii_30.zip
            |                       |       |       |___malaria_ecology.zip
            |                       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |                       |       |       |___gasflares.zip
            |                       |       |       |___F%sy%.v4.tar
            |                       |       |       |___boundaries.zip
            |                       |       |___world_avg.tif
            |                       |           |___v4unzip.bat
            |                       |               |___rad_cal.tar
            |                       |               |___phys_geo.zip
            |                       |               |___world_avg_fixed.tfw
            |                       |               |___af_grumpv1_ppoints_csv.zip
            |                       |               |___gl_grumpv1_area_ascii_30.zip
            |                       |               |___malaria_ecology.zip
            |                       |               |___gl_gpwv3_pcount_00_wrk_25.zip
            |                       |               |___gasflares.zip
            |                       |               |___F%sy%.v4.tar
            |                       |               |___boundaries.zip
            |                       |___isocvgst.dbf
            |                       |   |___pre_aml.do
            |                       |       |___afpv1.csv
            |                       |       |   |___v4unzip.bat
            |                       |       |       |___rad_cal.tar
            |                       |       |       |___phys_geo.zip
            |                       |       |       |___world_avg_fixed.tfw
            |                       |       |       |___af_grumpv1_ppoints_csv.zip
            |                       |       |       |___gl_grumpv1_area_ascii_30.zip
            |                       |       |       |___malaria_ecology.zip
            |                       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |                       |       |       |___gasflares.zip
            |                       |       |       |___F%sy%.v4.tar
            |                       |       |       |___boundaries.zip
            |                       |       |___ctrynum.dbf
            |                       |___ginistrt.dbf
            |                           |___pre_aml.do
            |                               |___afpv1.csv
            |                               |   |___v4unzip.bat
            |                               |       |___rad_cal.tar
            |                               |       |___phys_geo.zip
            |                               |       |___world_avg_fixed.tfw
            |                               |       |___af_grumpv1_ppoints_csv.zip
            |                               |       |___gl_grumpv1_area_ascii_30.zip
            |                               |       |___malaria_ecology.zip
            |                               |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |                               |       |___gasflares.zip
            |                               |       |___F%sy%.v4.tar
            |                               |       |___boundaries.zip
            |                               |___ctrynum.dbf
            |___samptab.txt
            |   |___v4lightsprep.aml
            |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
            |       |   |___v4unzip.bat
            |       |       |___rad_cal.tar
            |       |       |___phys_geo.zip
            |       |       |___world_avg_fixed.tfw
            |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |___malaria_ecology.zip
            |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |___gasflares.zip
            |       |       |___F%sy%.v4.tar
            |       |       |___boundaries.zip
            |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
            |       |   |___v4unzip.bat
            |       |       |___rad_cal.tar
            |       |       |___phys_geo.zip
            |       |       |___world_avg_fixed.tfw
            |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |___malaria_ecology.zip
            |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |___gasflares.zip
            |       |       |___F%sy%.v4.tar
            |       |       |___boundaries.zip
            |       |___world_avg.tfw
            |       |   |___v4unzip.bat
            |       |       |___rad_cal.tar
            |       |       |___phys_geo.zip
            |       |       |___world_avg_fixed.tfw
            |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |___malaria_ecology.zip
            |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |___gasflares.zip
            |       |       |___F%sy%.v4.tar
            |       |       |___boundaries.zip
            |       |___gluareag_alpha1.asc
            |       |   |___v4unzip.bat
            |       |       |___rad_cal.tar
            |       |       |___phys_geo.zip
            |       |       |___world_avg_fixed.tfw
            |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |___malaria_ecology.zip
            |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |___gasflares.zip
            |       |       |___F%sy%.v4.tar
            |       |       |___boundaries.zip
            |       |___F%sy%.v4b_web.cf_cvg.tif
            |       |   |___v4unzip.bat
            |       |       |___rad_cal.tar
            |       |       |___phys_geo.zip
            |       |       |___world_avg_fixed.tfw
            |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |___malaria_ecology.zip
            |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |___gasflares.zip
            |       |       |___F%sy%.v4.tar
            |       |       |___boundaries.zip
            |       |___F%sy%.v4b_web.cf_cvg.tfw
            |       |   |___v4unzip.bat
            |       |       |___rad_cal.tar
            |       |       |___phys_geo.zip
            |       |       |___world_avg_fixed.tfw
            |       |       |___af_grumpv1_ppoints_csv.zip
            |       |       |___gl_grumpv1_area_ascii_30.zip
            |       |       |___malaria_ecology.zip
            |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
            |       |       |___gasflares.zip
            |       |       |___F%sy%.v4.tar
            |       |       |___boundaries.zip
            |       |___world_avg.tif
            |           |___v4unzip.bat
            |               |___rad_cal.tar
            |               |___phys_geo.zip
            |               |___world_avg_fixed.tfw
            |               |___af_grumpv1_ppoints_csv.zip
            |               |___gl_grumpv1_area_ascii_30.zip
            |               |___malaria_ecology.zip
            |               |___gl_gpwv3_pcount_00_wrk_25.zip
            |               |___gasflares.zip
            |               |___F%sy%.v4.tar
            |               |___boundaries.zip
            |___global_total_dn_uncal.dta
                |___v4lights_stataprep_uncal.do
                    |___ctryoutu.dbf
                    |   |___v4ctrytables_uncal.aml
                    |       |___ctryliggrid
                    |       |   |___v4unzip.bat
                    |       |       |___rad_cal.tar
                    |       |       |___phys_geo.zip
                    |       |       |___world_avg_fixed.tfw
                    |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |___malaria_ecology.zip
                    |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |___gasflares.zip
                    |       |       |___F%sy%.v4.tar
                    |       |       |___boundaries.zip
                    |       |___l%sy%nm
                    |       |   |___v4lightsprep.aml
                    |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___world_avg.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___gluareag_alpha1.asc
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.cf_cvg.tif
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.cf_cvg.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___world_avg.tif
                    |       |           |___v4unzip.bat
                    |       |               |___rad_cal.tar
                    |       |               |___phys_geo.zip
                    |       |               |___world_avg_fixed.tfw
                    |       |               |___af_grumpv1_ppoints_csv.zip
                    |       |               |___gl_grumpv1_area_ascii_30.zip
                    |       |               |___malaria_ecology.zip
                    |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |               |___gasflares.zip
                    |       |               |___F%sy%.v4.tar
                    |       |               |___boundaries.zip
                    |       |___cvg%sy%
                    |       |   |___v4lightsprep.aml
                    |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___world_avg.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___gluareag_alpha1.asc
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.cf_cvg.tif
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.cf_cvg.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___world_avg.tif
                    |       |           |___v4unzip.bat
                    |       |               |___rad_cal.tar
                    |       |               |___phys_geo.zip
                    |       |               |___world_avg_fixed.tfw
                    |       |               |___af_grumpv1_ppoints_csv.zip
                    |       |               |___gl_grumpv1_area_ascii_30.zip
                    |       |               |___malaria_ecology.zip
                    |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |               |___gasflares.zip
                    |       |               |___F%sy%.v4.tar
                    |       |               |___boundaries.zip
                    |       |___gluareag
                    |       |   |___v4lightsprep.aml
                    |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___world_avg.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___gluareag_alpha1.asc
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.cf_cvg.tif
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.cf_cvg.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___world_avg.tif
                    |       |           |___v4unzip.bat
                    |       |               |___rad_cal.tar
                    |       |               |___phys_geo.zip
                    |       |               |___world_avg_fixed.tfw
                    |       |               |___af_grumpv1_ppoints_csv.zip
                    |       |               |___gl_grumpv1_area_ascii_30.zip
                    |       |               |___malaria_ecology.zip
                    |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |               |___gasflares.zip
                    |       |               |___F%sy%.v4.tar
                    |       |               |___boundaries.zip
                    |       |___ctrynum.dbf
                    |       |___gasflares.shp
                    |       |   |___merge_gf.pyw
                    |       |       |___afprimates.csv
                    |       |       |   |___pre_aml.do
                    |       |       |       |___afpv1.csv
                    |       |       |       |   |___v4unzip.bat
                    |       |       |       |       |___rad_cal.tar
                    |       |       |       |       |___phys_geo.zip
                    |       |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |       |___malaria_ecology.zip
                    |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |       |___gasflares.zip
                    |       |       |       |       |___F%sy%.v4.tar
                    |       |       |       |       |___boundaries.zip
                    |       |       |       |___ctrynum.dbf
                    |       |       |___gas flares by country
                    |       |           |___v4unzip.bat
                    |       |               |___rad_cal.tar
                    |       |               |___phys_geo.zip
                    |       |               |___world_avg_fixed.tfw
                    |       |               |___af_grumpv1_ppoints_csv.zip
                    |       |               |___gl_grumpv1_area_ascii_30.zip
                    |       |               |___malaria_ecology.zip
                    |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |               |___gasflares.zip
                    |       |               |___F%sy%.v4.tar
                    |       |               |___boundaries.zip
                    |       |___glp00ag
                    |           |___v4unzip.bat
                    |               |___rad_cal.tar
                    |               |___phys_geo.zip
                    |               |___world_avg_fixed.tfw
                    |               |___af_grumpv1_ppoints_csv.zip
                    |               |___gl_grumpv1_area_ascii_30.zip
                    |               |___malaria_ecology.zip
                    |               |___gl_gpwv3_pcount_00_wrk_25.zip
                    |               |___gasflares.zip
                    |               |___F%sy%.v4.tar
                    |               |___boundaries.zip
                    |___dhselect.xls
                    |___wb_dq.xls
                    |___ctryout2.dbf
                    |   |___v4ctrytables_uncal.aml
                    |       |___ctryliggrid
                    |       |   |___v4unzip.bat
                    |       |       |___rad_cal.tar
                    |       |       |___phys_geo.zip
                    |       |       |___world_avg_fixed.tfw
                    |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |___malaria_ecology.zip
                    |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |___gasflares.zip
                    |       |       |___F%sy%.v4.tar
                    |       |       |___boundaries.zip
                    |       |___l%sy%nm
                    |       |   |___v4lightsprep.aml
                    |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___world_avg.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___gluareag_alpha1.asc
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.cf_cvg.tif
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.cf_cvg.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___world_avg.tif
                    |       |           |___v4unzip.bat
                    |       |               |___rad_cal.tar
                    |       |               |___phys_geo.zip
                    |       |               |___world_avg_fixed.tfw
                    |       |               |___af_grumpv1_ppoints_csv.zip
                    |       |               |___gl_grumpv1_area_ascii_30.zip
                    |       |               |___malaria_ecology.zip
                    |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |               |___gasflares.zip
                    |       |               |___F%sy%.v4.tar
                    |       |               |___boundaries.zip
                    |       |___cvg%sy%
                    |       |   |___v4lightsprep.aml
                    |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___world_avg.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___gluareag_alpha1.asc
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.cf_cvg.tif
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.cf_cvg.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___world_avg.tif
                    |       |           |___v4unzip.bat
                    |       |               |___rad_cal.tar
                    |       |               |___phys_geo.zip
                    |       |               |___world_avg_fixed.tfw
                    |       |               |___af_grumpv1_ppoints_csv.zip
                    |       |               |___gl_grumpv1_area_ascii_30.zip
                    |       |               |___malaria_ecology.zip
                    |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |               |___gasflares.zip
                    |       |               |___F%sy%.v4.tar
                    |       |               |___boundaries.zip
                    |       |___gluareag
                    |       |   |___v4lightsprep.aml
                    |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___world_avg.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___gluareag_alpha1.asc
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.cf_cvg.tif
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.cf_cvg.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___world_avg.tif
                    |       |           |___v4unzip.bat
                    |       |               |___rad_cal.tar
                    |       |               |___phys_geo.zip
                    |       |               |___world_avg_fixed.tfw
                    |       |               |___af_grumpv1_ppoints_csv.zip
                    |       |               |___gl_grumpv1_area_ascii_30.zip
                    |       |               |___malaria_ecology.zip
                    |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |               |___gasflares.zip
                    |       |               |___F%sy%.v4.tar
                    |       |               |___boundaries.zip
                    |       |___ctrynum.dbf
                    |       |___gasflares.shp
                    |       |   |___merge_gf.pyw
                    |       |       |___afprimates.csv
                    |       |       |   |___pre_aml.do
                    |       |       |       |___afpv1.csv
                    |       |       |       |   |___v4unzip.bat
                    |       |       |       |       |___rad_cal.tar
                    |       |       |       |       |___phys_geo.zip
                    |       |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |       |___malaria_ecology.zip
                    |       |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |       |___gasflares.zip
                    |       |       |       |       |___F%sy%.v4.tar
                    |       |       |       |       |___boundaries.zip
                    |       |       |       |___ctrynum.dbf
                    |       |       |___gas flares by country
                    |       |           |___v4unzip.bat
                    |       |               |___rad_cal.tar
                    |       |               |___phys_geo.zip
                    |       |               |___world_avg_fixed.tfw
                    |       |               |___af_grumpv1_ppoints_csv.zip
                    |       |               |___gl_grumpv1_area_ascii_30.zip
                    |       |               |___malaria_ecology.zip
                    |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |               |___gasflares.zip
                    |       |               |___F%sy%.v4.tar
                    |       |               |___boundaries.zip
                    |       |___glp00ag
                    |           |___v4unzip.bat
                    |               |___rad_cal.tar
                    |               |___phys_geo.zip
                    |               |___world_avg_fixed.tfw
                    |               |___af_grumpv1_ppoints_csv.zip
                    |               |___gl_grumpv1_area_ascii_30.zip
                    |               |___malaria_ecology.zip
                    |               |___gl_gpwv3_pcount_00_wrk_25.zip
                    |               |___gasflares.zip
                    |               |___F%sy%.v4.tar
                    |               |___boundaries.zip
                    |___ginioutu.dbf
                    |   |___v4cvggini_bycountry_prep.aml
                    |       |___ctryliggrid
                    |       |   |___v4unzip.bat
                    |       |       |___rad_cal.tar
                    |       |       |___phys_geo.zip
                    |       |       |___world_avg_fixed.tfw
                    |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |___malaria_ecology.zip
                    |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |___gasflares.zip
                    |       |       |___F%sy%.v4.tar
                    |       |       |___boundaries.zip
                    |       |___l%sy%nm
                    |       |   |___v4lightsprep.aml
                    |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___world_avg.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___gluareag_alpha1.asc
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.cf_cvg.tif
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.cf_cvg.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___world_avg.tif
                    |       |           |___v4unzip.bat
                    |       |               |___rad_cal.tar
                    |       |               |___phys_geo.zip
                    |       |               |___world_avg_fixed.tfw
                    |       |               |___af_grumpv1_ppoints_csv.zip
                    |       |               |___gl_grumpv1_area_ascii_30.zip
                    |       |               |___malaria_ecology.zip
                    |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |               |___gasflares.zip
                    |       |               |___F%sy%.v4.tar
                    |       |               |___boundaries.zip
                    |       |___cvg%sy%
                    |       |   |___v4lightsprep.aml
                    |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___world_avg.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___gluareag_alpha1.asc
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.cf_cvg.tif
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___F%sy%.v4b_web.cf_cvg.tfw
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___world_avg.tif
                    |       |           |___v4unzip.bat
                    |       |               |___rad_cal.tar
                    |       |               |___phys_geo.zip
                    |       |               |___world_avg_fixed.tfw
                    |       |               |___af_grumpv1_ppoints_csv.zip
                    |       |               |___gl_grumpv1_area_ascii_30.zip
                    |       |               |___malaria_ecology.zip
                    |       |               |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |               |___gasflares.zip
                    |       |               |___F%sy%.v4.tar
                    |       |               |___boundaries.zip
                    |       |___isocvgst.dbf
                    |       |   |___pre_aml.do
                    |       |       |___afpv1.csv
                    |       |       |   |___v4unzip.bat
                    |       |       |       |___rad_cal.tar
                    |       |       |       |___phys_geo.zip
                    |       |       |       |___world_avg_fixed.tfw
                    |       |       |       |___af_grumpv1_ppoints_csv.zip
                    |       |       |       |___gl_grumpv1_area_ascii_30.zip
                    |       |       |       |___malaria_ecology.zip
                    |       |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |       |       |       |___gasflares.zip
                    |       |       |       |___F%sy%.v4.tar
                    |       |       |       |___boundaries.zip
                    |       |       |___ctrynum.dbf
                    |       |___ginistrt.dbf
                    |           |___pre_aml.do
                    |               |___afpv1.csv
                    |               |   |___v4unzip.bat
                    |               |       |___rad_cal.tar
                    |               |       |___phys_geo.zip
                    |               |       |___world_avg_fixed.tfw
                    |               |       |___af_grumpv1_ppoints_csv.zip
                    |               |       |___gl_grumpv1_area_ascii_30.zip
                    |               |       |___malaria_ecology.zip
                    |               |       |___gl_gpwv3_pcount_00_wrk_25.zip
                    |               |       |___gasflares.zip
                    |               |       |___F%sy%.v4.tar
                    |               |       |___boundaries.zip
                    |               |___ctrynum.dbf
                    |___wdi_limited.dta
                    |___imf_dds.xls
                    |___ginistata_uncal.dta
                        |___v4ginicalc_uncal.do
                            |___ginioutu.dbf
                                |___v4cvggini_bycountry_prep.aml
                                    |___ctryliggrid
                                    |   |___v4unzip.bat
                                    |       |___rad_cal.tar
                                    |       |___phys_geo.zip
                                    |       |___world_avg_fixed.tfw
                                    |       |___af_grumpv1_ppoints_csv.zip
                                    |       |___gl_grumpv1_area_ascii_30.zip
                                    |       |___malaria_ecology.zip
                                    |       |___gl_gpwv3_pcount_00_wrk_25.zip
                                    |       |___gasflares.zip
                                    |       |___F%sy%.v4.tar
                                    |       |___boundaries.zip
                                    |___l%sy%nm
                                    |   |___v4lightsprep.aml
                                    |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
                                    |       |   |___v4unzip.bat
                                    |       |       |___rad_cal.tar
                                    |       |       |___phys_geo.zip
                                    |       |       |___world_avg_fixed.tfw
                                    |       |       |___af_grumpv1_ppoints_csv.zip
                                    |       |       |___gl_grumpv1_area_ascii_30.zip
                                    |       |       |___malaria_ecology.zip
                                    |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                                    |       |       |___gasflares.zip
                                    |       |       |___F%sy%.v4.tar
                                    |       |       |___boundaries.zip
                                    |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
                                    |       |   |___v4unzip.bat
                                    |       |       |___rad_cal.tar
                                    |       |       |___phys_geo.zip
                                    |       |       |___world_avg_fixed.tfw
                                    |       |       |___af_grumpv1_ppoints_csv.zip
                                    |       |       |___gl_grumpv1_area_ascii_30.zip
                                    |       |       |___malaria_ecology.zip
                                    |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                                    |       |       |___gasflares.zip
                                    |       |       |___F%sy%.v4.tar
                                    |       |       |___boundaries.zip
                                    |       |___world_avg.tfw
                                    |       |   |___v4unzip.bat
                                    |       |       |___rad_cal.tar
                                    |       |       |___phys_geo.zip
                                    |       |       |___world_avg_fixed.tfw
                                    |       |       |___af_grumpv1_ppoints_csv.zip
                                    |       |       |___gl_grumpv1_area_ascii_30.zip
                                    |       |       |___malaria_ecology.zip
                                    |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                                    |       |       |___gasflares.zip
                                    |       |       |___F%sy%.v4.tar
                                    |       |       |___boundaries.zip
                                    |       |___gluareag_alpha1.asc
                                    |       |   |___v4unzip.bat
                                    |       |       |___rad_cal.tar
                                    |       |       |___phys_geo.zip
                                    |       |       |___world_avg_fixed.tfw
                                    |       |       |___af_grumpv1_ppoints_csv.zip
                                    |       |       |___gl_grumpv1_area_ascii_30.zip
                                    |       |       |___malaria_ecology.zip
                                    |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                                    |       |       |___gasflares.zip
                                    |       |       |___F%sy%.v4.tar
                                    |       |       |___boundaries.zip
                                    |       |___F%sy%.v4b_web.cf_cvg.tif
                                    |       |   |___v4unzip.bat
                                    |       |       |___rad_cal.tar
                                    |       |       |___phys_geo.zip
                                    |       |       |___world_avg_fixed.tfw
                                    |       |       |___af_grumpv1_ppoints_csv.zip
                                    |       |       |___gl_grumpv1_area_ascii_30.zip
                                    |       |       |___malaria_ecology.zip
                                    |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                                    |       |       |___gasflares.zip
                                    |       |       |___F%sy%.v4.tar
                                    |       |       |___boundaries.zip
                                    |       |___F%sy%.v4b_web.cf_cvg.tfw
                                    |       |   |___v4unzip.bat
                                    |       |       |___rad_cal.tar
                                    |       |       |___phys_geo.zip
                                    |       |       |___world_avg_fixed.tfw
                                    |       |       |___af_grumpv1_ppoints_csv.zip
                                    |       |       |___gl_grumpv1_area_ascii_30.zip
                                    |       |       |___malaria_ecology.zip
                                    |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                                    |       |       |___gasflares.zip
                                    |       |       |___F%sy%.v4.tar
                                    |       |       |___boundaries.zip
                                    |       |___world_avg.tif
                                    |           |___v4unzip.bat
                                    |               |___rad_cal.tar
                                    |               |___phys_geo.zip
                                    |               |___world_avg_fixed.tfw
                                    |               |___af_grumpv1_ppoints_csv.zip
                                    |               |___gl_grumpv1_area_ascii_30.zip
                                    |               |___malaria_ecology.zip
                                    |               |___gl_gpwv3_pcount_00_wrk_25.zip
                                    |               |___gasflares.zip
                                    |               |___F%sy%.v4.tar
                                    |               |___boundaries.zip
                                    |___cvg%sy%
                                    |   |___v4lightsprep.aml
                                    |       |___F%sy%.v4b_web.stable_lights.avg_vis.tfw
                                    |       |   |___v4unzip.bat
                                    |       |       |___rad_cal.tar
                                    |       |       |___phys_geo.zip
                                    |       |       |___world_avg_fixed.tfw
                                    |       |       |___af_grumpv1_ppoints_csv.zip
                                    |       |       |___gl_grumpv1_area_ascii_30.zip
                                    |       |       |___malaria_ecology.zip
                                    |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                                    |       |       |___gasflares.zip
                                    |       |       |___F%sy%.v4.tar
                                    |       |       |___boundaries.zip
                                    |       |___F%sy%.v4b_web.stable_lights.avg_vis.tif
                                    |       |   |___v4unzip.bat
                                    |       |       |___rad_cal.tar
                                    |       |       |___phys_geo.zip
                                    |       |       |___world_avg_fixed.tfw
                                    |       |       |___af_grumpv1_ppoints_csv.zip
                                    |       |       |___gl_grumpv1_area_ascii_30.zip
                                    |       |       |___malaria_ecology.zip
                                    |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                                    |       |       |___gasflares.zip
                                    |       |       |___F%sy%.v4.tar
                                    |       |       |___boundaries.zip
                                    |       |___world_avg.tfw
                                    |       |   |___v4unzip.bat
                                    |       |       |___rad_cal.tar
                                    |       |       |___phys_geo.zip
                                    |       |       |___world_avg_fixed.tfw
                                    |       |       |___af_grumpv1_ppoints_csv.zip
                                    |       |       |___gl_grumpv1_area_ascii_30.zip
                                    |       |       |___malaria_ecology.zip
                                    |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                                    |       |       |___gasflares.zip
                                    |       |       |___F%sy%.v4.tar
                                    |       |       |___boundaries.zip
                                    |       |___gluareag_alpha1.asc
                                    |       |   |___v4unzip.bat
                                    |       |       |___rad_cal.tar
                                    |       |       |___phys_geo.zip
                                    |       |       |___world_avg_fixed.tfw
                                    |       |       |___af_grumpv1_ppoints_csv.zip
                                    |       |       |___gl_grumpv1_area_ascii_30.zip
                                    |       |       |___malaria_ecology.zip
                                    |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                                    |       |       |___gasflares.zip
                                    |       |       |___F%sy%.v4.tar
                                    |       |       |___boundaries.zip
                                    |       |___F%sy%.v4b_web.cf_cvg.tif
                                    |       |   |___v4unzip.bat
                                    |       |       |___rad_cal.tar
                                    |       |       |___phys_geo.zip
                                    |       |       |___world_avg_fixed.tfw
                                    |       |       |___af_grumpv1_ppoints_csv.zip
                                    |       |       |___gl_grumpv1_area_ascii_30.zip
                                    |       |       |___malaria_ecology.zip
                                    |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                                    |       |       |___gasflares.zip
                                    |       |       |___F%sy%.v4.tar
                                    |       |       |___boundaries.zip
                                    |       |___F%sy%.v4b_web.cf_cvg.tfw
                                    |       |   |___v4unzip.bat
                                    |       |       |___rad_cal.tar
                                    |       |       |___phys_geo.zip
                                    |       |       |___world_avg_fixed.tfw
                                    |       |       |___af_grumpv1_ppoints_csv.zip
                                    |       |       |___gl_grumpv1_area_ascii_30.zip
                                    |       |       |___malaria_ecology.zip
                                    |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                                    |       |       |___gasflares.zip
                                    |       |       |___F%sy%.v4.tar
                                    |       |       |___boundaries.zip
                                    |       |___world_avg.tif
                                    |           |___v4unzip.bat
                                    |               |___rad_cal.tar
                                    |               |___phys_geo.zip
                                    |               |___world_avg_fixed.tfw
                                    |               |___af_grumpv1_ppoints_csv.zip
                                    |               |___gl_grumpv1_area_ascii_30.zip
                                    |               |___malaria_ecology.zip
                                    |               |___gl_gpwv3_pcount_00_wrk_25.zip
                                    |               |___gasflares.zip
                                    |               |___F%sy%.v4.tar
                                    |               |___boundaries.zip
                                    |___isocvgst.dbf
                                    |   |___pre_aml.do
                                    |       |___afpv1.csv
                                    |       |   |___v4unzip.bat
                                    |       |       |___rad_cal.tar
                                    |       |       |___phys_geo.zip
                                    |       |       |___world_avg_fixed.tfw
                                    |       |       |___af_grumpv1_ppoints_csv.zip
                                    |       |       |___gl_grumpv1_area_ascii_30.zip
                                    |       |       |___malaria_ecology.zip
                                    |       |       |___gl_gpwv3_pcount_00_wrk_25.zip
                                    |       |       |___gasflares.zip
                                    |       |       |___F%sy%.v4.tar
                                    |       |       |___boundaries.zip
                                    |       |___ctrynum.dbf
                                    |___ginistrt.dbf
                                        |___pre_aml.do
                                            |___afpv1.csv
                                            |   |___v4unzip.bat
                                            |       |___rad_cal.tar
                                            |       |___phys_geo.zip
                                            |       |___world_avg_fixed.tfw
                                            |       |___af_grumpv1_ppoints_csv.zip
                                            |       |___gl_grumpv1_area_ascii_30.zip
                                            |       |___malaria_ecology.zip
                                            |       |___gl_gpwv3_pcount_00_wrk_25.zip
                                            |       |___gasflares.zip
                                            |       |___F%sy%.v4.tar
                                            |       |___boundaries.zip
                                            |___ctrynum.dbf

```
