
# Tips and Resources for Reproducible Workflow


## Reproducible workflows:  

Below is a summary from Chapter 11 of @christensen2019transparent. If there is a book/chapter that you find particularly helpful for, please write a brief summary and submit a [contribution](#contrib-guide). 

**Folder organization**

Basic file organization is a critical component of a reproducible workflow. The following structure is recommended, but can be adapted to accommodate different reproducers or types of research. The name of the master folder should be easy to read and meaningful to all collaborators on the the project.

- Create a master folder with a descriptive name for the project. It should contain:
  - Separate folders for programming script files, raw data, edited data, output, and final paper or article text
  - A README file: description of contents of each folder, as well as installation and operating instructions for reproducers
- Keep raw data intact: Any edits or datasets generated using raw data should be stored in a "data" folder separate from the "raw data" folder.
- When naming a directory or file, stick to lowercase letters with underscores (instead of spaces) to avoid cross-operating-system issues.

**Efficient and readable programming**

The core of programming for reproducibility is to write code wherever possible. Writing scripts leaves a record of any changes to data, which allows other researchers to reproduce work exactly. It is also helpful to leave comments in your code to explain the reasoning for changes or any gaps left if using point-and-click methods is necessary.    

- Leave a record of any changes to the data: Write code in the programming environment, instead of modifying data by hand in a spreadsheet or relying on point-and-click options.
- Include comments in code to explain changes, and save intermediate datasets used in analysis.
- Give variables names that will be informative to reproducers.
- Use relative directory paths, not absolute paths, so the work can be more easily reproduced from different computers.  

**Version control**  

Version control software is used to keep a record of changes to project files. Although it is possible to manually track changes in a central research log or as notes in individual script files, many social scientists recognize the benefits of a distributed version control system. Because each collaborator is able to have a local copy of the project's entire work history, these systems are particularly suited to collaborative projects. Below are methods to manually track changes and a brief explanation of Git, a popular distributed version control system.  

- Maintain a written record of work.
  - In a central research log: Log activities in a single central file as often as work on the project is being done (keep track of "which team member writes what code, produces what output, edits which files, and when").
  - In individual script files: Record "who edited which part of which file when, and why."
  - With a version control system, such as Git: Git records changes made to files, by whom, and when.
- A brief explanation of Git: Users add changed files to the staging area, then commit those changes to the project folder, or repository. Git keeps the filename and records the new version of each file from the staging area.


## Links to resources, organizations and people for reproducibile work

Below we point to an ever growing list of resouces, organizations and specific researcher doing empirical work with a strong orientation towards reproducibility. The list are alphabetical order and [contributions](#contrib-guide) are welcome! 

### Resources
- Dynamic documents in [R](https://rmarkdown.rstudio.com/gallery.html), [Python](https://github.com/jupyter/jupyter/wiki/A-gallery-of-interesting-Jupyter-Notebooks#economics-and-finance) and [Stata](https://github.com/BITSS/CEGA2019/blob/master/03-extra_dynamic_docs/02b-Stata-markdown/Stata%20Markdown.pdf)  
- Git resources:   
  - [Jenny Bryan's book](https://happygitwithr.com) and [video](https://www.rstudio.com/resources/videos/happy-git-and-gihub-for-the-user-tutorial/)  
  - [Github learning lab](https://lab.github.com/)
  - [Udacity's intro](https://www.udacity.com/course/how-to-use-git-and-github--ud775)  
  - [Git for poets](https://www.youtube.com/playlist?list=PLRqwX-V7Uu6ZF9C0YMKuns9sLDzK6zoiV)  
  - [Combining GitHub and Dropbox](https://github.com/kbjarkefur/GitHubDropBox)    
  - [Atlassian intro to Git](https://www.atlassian.com/git/tutorials)
  - [Software Carpentry tutorial from the command line](https://swcarpentry.github.io/git-novice/)
  
- [IDB's cheatsheet for transparency, reproducibility and ethics](http://idbdocs.iadb.org/wsdocs/getdocument.aspx?docnum=EZSHARE-1350314980-383)   
- [Lars Vilhuber LDI's Wiki for Reproducibility](https://github.com/labordynamicsinstitute/replicability-training/wiki). Particularly [this section](https://github.com/labordynamicsinstitute/replicability-training/wiki/Prepare_and_run_replication).  
- [Open Science Framework (OSF)](https://osf.io)
- [Project TIER](https://www.projecttier.org/tier-protocol/)   
- [R for Stata users](https://github.com/hblackburn/R4Econ/blob/master/Resources.md)  
- World Bank [DIME's Wiki for transparent and reproducible research](https://dimewiki.worldbank.org/wiki/Main_Page).

### Organizations

- [Congressional Budget Office](https://github.com/US-CBO)
- [Gentzkow & Shapiro Lab](https://github.com/gslab-econ)
- [LOST](https://lost-stats.github.io/)
- [Opportunity Lab](https://github.com/Opportunitylab)
- [Policy Simulation Library](https://github.com/PSLmodels)
- [Urban Institute](https://github.com/UrbanInstitute)


### People

(by last name)

- [Luiza Andrade](https://github.com/luizaandrade)
- [Alvaro Carril](https://github.com/acarril)
- [Lachlan Deer](https://github.com/lachlandeer) 
- [Rebekah Din](https://github.com/rebekahanne)
- [Richard Evans](https://github.com/rickecon)
- [Andrew Heiss](https://github.com/andrewheiss)
- [John Horton](https://github.com/johnjosephhorton)
- [Nick Huntingon](https://github.com/NickCH-K) 
- [Matt Jensen](https://github.com/MattHJensen)
- [Max Kasy](https://github.com/maxkasy)
- [Cora Kingdon](https://github.com/ckingdon95)
- [Grant McDermott](https://github.com/grantmcdermott)
- [Tyler Ransom](https://github.com/tyleransom)
- [Lisa Rennels](https://github.com/lrennels)
- [Ed Rubin](https://github.com/edrubin)
- [Michael Stepner](https://github.com/michaelstepner)
- [Shoshana Vasserman](https://github.com/shoshievass)  
- [Lars Vilhuber](https://github.com/larsvilhuber)




[1]: Non-exhaustive list of people and organizations doing amazing reproducible work on github (other than us!)
