# Tips for Communication

[UNDER CONSTRUCTION]

## For students or researchers conducting a reproduction  

### Contacting the Authors of the Original Study

#### Verify in the ACRE database, if authors have been contacted before

#### Email them     

##### Template language   
[draft here](https://docs.google.com/document/d/1xJ7pZTQ1VQXVCrs6IUlp7HlBB4oxYha0oOniCG2SWLM/edit?ts=5d251563)

Remember to link template language to documentation for later, to check with team  

###### Requesting raw/analytic data and code  
###### Following up on a non-response requesting additional contact information
  - point out the level of reproducibility of project and how to improve 
  
###### Reporting improvements done to current reproducibility package

###### Requestion permission to re-post public data in new reproduction packages  
Would like to repost your data  
You already gave permission to authors XYZ  
Just trying to improve this authors reproducibility  
Your permission would allow students and researchers do more work in this area.  


###### If response  

Follow up with request of steps necessary for any researcher in the future to access this data.  



 - **Coding errors:**  a coding error will occur when a section in the code, of the reproduction package, executes a procedure that is in direct contradiction with the intended procedure expressed in the documentation (paper or comments of the code). For example an error happens if the paper specify that the analysis is perform on the population of males, but the code restricts the analysis to females only. Please follow the [ACRE procedure to report coding errors](ADD LINK).  


## For original authors contacted by reproductors

## Responding to inquiries




